apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  ports:
    - name: '3010-3000'
      port: 3010 # Puerto en el que el servicio está disponible internamente en el clúster
      protocol: TCP
      targetPort: 3000 # Puerto en el que los contenedores (la app) de los Pods están escuchando
  selector:
    app: payments-ms
  type: NodePort
status:
  loadBalancer: {}
