name: nest-microservices

services:
  rabbitmq-server:
    restart: unless-stopped
    container_name: rabbitmq-server
    image: rabbitmq:3.12.14-management-alpine
    ports:
      - ${RABBITMQ_UI_PORT}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq-server-volume:/var/lib/rabbitmq

  redis-server:
    container_name: redis_server
    restart: unless-stopped
    image: redis:alpine3.20
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis-server-volume:/data

  client-gateway:
    restart: unless-stopped
    container_name: client-gateway
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/microservices-nest-dev/register-nest-dev/nest-microservices-client-gateway:1.0.0
    environment:
      - RABBITMQ_SERVER=${RABBITMQ_SERVER}
      - PORT=${GATEWAY_PORT}
    ports:
      - '${GATEWAY_PORT}:3000'

  orders-ms:
    depends_on:
      - rabbitmq-server
    restart: unless-stopped
    container_name: orders-ms
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: southamerica-west1-docker.pkg.dev/microservices-nest-dev/register-nest-dev/nest-microservices-orders:1.0.0
    environment:
      - DATABASE_URL=${ORDERS_DATABASE_URL}
      - RABBITMQ_SERVER=${RABBITMQ_SERVER}
      - PORT=${ORDERS_PORT}

  products-ms:
    depends_on:
      - rabbitmq-server
      - redis-server
    restart: unless-stopped
    container_name: products-ms
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/microservices-nest-dev/register-nest-dev/nest-microservices-products:1.0.0
    environment:
      - DATABASE_URL=${PRODUCTS_DATABASE_URL}
      - RABBITMQ_SERVER=${RABBITMQ_SERVER}
      - PORT=${PRODUCTS_PORT}

  payments-ms:
    depends_on:
      - rabbitmq-server
    restart: unless-stopped
    container_name: payments-ms
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/microservices-nest-dev/register-nest-dev/nest-microservices-payments:1.0.0
    ports:
      - '${PAYMENTS_PORT}:3000'
    environment:
      - PORT=${PAYMENTS_PORT}
      - STRIPE_API_KEY=${PAYMENTS_STRIPE_API_KEY}
      - SUCCESS_URL=${PAYMENTS_SUCCESS_URL}
      - CANCEL_URL=${PAYMENTS_CANCEL_URL}
      - ENDPOINT_SECRET=${PAYMENTS_ENDPOINT_SECRET}
      - RABBITMQ_SERVER=${RABBITMQ_SERVER}

  auth-ms:
    depends_on:
      - rabbitmq-server
    restart: unless-stopped
    container_name: auth-ms
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/microservices-nest-dev/register-nest-dev/nest-microservices-auth:1.0.0
    environment:
      - PORT=${AUTH_PORT}
      - RABBITMQ_SERVER=${RABBITMQ_SERVER}
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${AUTH_JWT_SECRET}

volumes:
  rabbitmq-server-volume:
  redis-server-volume:
